

package com.fueledbycaffeine.autoservice.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.fueledbycaffeine.autoservice.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  private void run(String fileName) {
    runTest("compiler-plugin/testData/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("GoogleAnnotation.kt")
  public void testGoogleAnnotation() {
    run("GoogleAnnotation.kt");
  }

  @Test
  @TestMetadata("InferredServiceInterface.kt")
  public void testInferredServiceInterface() {
    run("InferredServiceInterface.kt");
  }

  @Test
  @TestMetadata("MultipleImplementations.kt")
  public void testMultipleImplementations() {
    run("MultipleImplementations.kt");
  }

  @Test
  @TestMetadata("MultipleServiceInterfaces.kt")
  public void testMultipleServiceInterfaces() {
    run("MultipleServiceInterfaces.kt");
  }

  @Test
  @TestMetadata("NestedClassProvider.kt")
  public void testNestedClassProvider() {
    run("NestedClassProvider.kt");
  }

  @Test
  @TestMetadata("SingleServiceImplementation.kt")
  public void testSingleServiceImplementation() {
    run("SingleServiceImplementation.kt");
  }
}
