

package com.fueledbycaffeine.autoservice.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.fueledbycaffeine.autoservice.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("GoogleAnnotation.kt")
  public void testGoogleAnnotation() {
    runTest("compiler-plugin/testData/box/GoogleAnnotation.kt");
  }

  @Test
  @TestMetadata("InferredServiceInterface.kt")
  public void testInferredServiceInterface() {
    runTest("compiler-plugin/testData/box/InferredServiceInterface.kt");
  }

  @Test
  @TestMetadata("MultipleImplementations.kt")
  public void testMultipleImplementations() {
    runTest("compiler-plugin/testData/box/MultipleImplementations.kt");
  }

  @Test
  @TestMetadata("MultipleServiceInterfaces.kt")
  public void testMultipleServiceInterfaces() {
    runTest("compiler-plugin/testData/box/MultipleServiceInterfaces.kt");
  }

  @Test
  @TestMetadata("NestedClassProvider.kt")
  public void testNestedClassProvider() {
    runTest("compiler-plugin/testData/box/NestedClassProvider.kt");
  }

  @Test
  @TestMetadata("SingleServiceImplementation.kt")
  public void testSingleServiceImplementation() {
    runTest("compiler-plugin/testData/box/SingleServiceImplementation.kt");
  }
}
