

package com.fueledbycaffeine.autoservice.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.fueledbycaffeine.autoservice.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticTestGenerated extends AbstractDiagnosticTest {
  @Test
  @TestMetadata("AbstractClass.kt")
  public void testAbstractClass() {
    runTest("compiler-plugin/testData/diagnostic/AbstractClass.kt");
  }

  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("AmbiguousInterface.kt")
  public void testAmbiguousInterface() {
    runTest("compiler-plugin/testData/diagnostic/AmbiguousInterface.kt");
  }

  @Test
  @TestMetadata("DoesNotImplement.kt")
  public void testDoesNotImplement() {
    runTest("compiler-plugin/testData/diagnostic/DoesNotImplement.kt");
  }

  @Test
  @TestMetadata("InterfaceAnnotated.kt")
  public void testInterfaceAnnotated() {
    runTest("compiler-plugin/testData/diagnostic/InterfaceAnnotated.kt");
  }

  @Test
  @TestMetadata("PrivateClass.kt")
  public void testPrivateClass() {
    runTest("compiler-plugin/testData/diagnostic/PrivateClass.kt");
  }
}
